"""Analytic (continuous-time) synthetic stimuli used as *independent truth*.

Every component is defined as a closed-form function of continuous time ``t``
so a "captured" version with a known clock ratio, delay, polarity, gain and DC
can be generated by direct evaluation at perturbed instants — without using the
evaluator's own resampler. This is what makes CHAIN-EXP-016 an independent
self-test rather than a resampler testing itself.

Nothing here models hardware. Levels are normalized units (1.0 = digital full
scale of the synthetic record); no volts are implied.
"""
from __future__ import annotations

from dataclasses import dataclass, field, asdict

import numpy as np

TWO_PI = 2.0 * np.pi


def raised_cosine_window(t: np.ndarray, t0: float, t1: float, edge: float) -> np.ndarray:
    """Smooth 0→1→0 envelope between t0 and t1 with raised-cosine edges of length ``edge`` (s)."""
    w = np.zeros_like(t, dtype=np.float64)
    inside = (t >= t0) & (t < t1)
    w[inside] = 1.0
    if edge > 0:
        up = (t >= t0) & (t < t0 + edge)
        dn = (t >= t1 - edge) & (t < t1)
        w[up] = 0.5 - 0.5 * np.cos(np.pi * (t[up] - t0) / edge)
        w[dn] = 0.5 - 0.5 * np.cos(np.pi * (t1 - t[dn]) / edge)
    return w


@dataclass(frozen=True)
class Tone:
    freq_hz: float
    amplitude: float
    phase_rad: float = 0.0


@dataclass
class Segment:
    name: str
    start_s: float
    duration_s: float
    tones: list[Tone] = field(default_factory=list)
    edge_s: float = 0.005
    role: str = "program"  # pilot_start | pilot_end | calibration | program | silence

    @property
    def end_s(self) -> float:
        return self.start_s + self.duration_s

    def evaluate(self, t: np.ndarray) -> np.ndarray:
        if not self.tones:
            return np.zeros_like(t, dtype=np.float64)
        w = raised_cosine_window(t, self.start_s, self.end_s, self.edge_s)
        y = np.zeros_like(t, dtype=np.float64)
        for tone in self.tones:
            y += tone.amplitude * np.sin(TWO_PI * tone.freq_hz * (t - self.start_s) + tone.phase_rad)
        return w * y


@dataclass
class Stimulus:
    """A list of non-overlapping analytic segments."""

    sample_rate_hz: int
    segments: list[Segment]
    description: str = ""

    @property
    def duration_s(self) -> float:
        return max(s.end_s for s in self.segments)

    def evaluate(self, t: np.ndarray) -> np.ndarray:
        y = np.zeros_like(np.asarray(t, dtype=np.float64))
        for s in self.segments:
            y += s.evaluate(np.asarray(t, dtype=np.float64))
        return y

    def render(self) -> np.ndarray:
        n = int(round(self.duration_s * self.sample_rate_hz))
        t = np.arange(n, dtype=np.float64) / self.sample_rate_hz
        return self.evaluate(t)

    def render_perturbed(self, clock_ratio: float = 1.0, delay_s: float = 0.0, polarity: int = 1,
                         gain: float = 1.0, dc: float = 0.0, n_samples: int | None = None) -> np.ndarray:
        """Independent truth for a 'capture': y[n] = gain*polarity*x(n*ratio/fs - delay) + dc.

        ``clock_ratio`` > 1 means the capture clock is slow relative to the
        source (tones appear higher in frequency by the ratio).
        """
        if n_samples is None:
            n_samples = int(round(self.duration_s * self.sample_rate_hz))
        n = np.arange(n_samples, dtype=np.float64)
        t = n * clock_ratio / self.sample_rate_hz - delay_s
        return gain * float(polarity) * self.evaluate(t) + dc

    def segment(self, role: str) -> Segment:
        for s in self.segments:
            if s.role == role:
                return s
        raise KeyError(role)

    def to_dict(self) -> dict:
        return {
            "sample_rate_hz": self.sample_rate_hz,
            "description": self.description,
            "segments": [
                {**asdict(s), "tones": [asdict(tn) for tn in s.tones]} for s in self.segments
            ],
        }


def multitone(n_tones: int, f_lo: float, f_hi: float, seed: int, peak: float) -> list[Tone]:
    """Log-spaced multitone with seeded random phases, scaled so the steady-state peak equals ``peak``."""
    rng = np.random.default_rng(seed)
    freqs = np.geomspace(f_lo, f_hi, n_tones)
    phases = rng.uniform(0, TWO_PI, n_tones)
    # Evaluate one second at a high rate to find the peak of the sum with unit amplitudes.
    fs_probe = 192000
    t = np.arange(fs_probe) / fs_probe
    s = np.zeros_like(t)
    for f, p in zip(freqs, phases):
        s += np.sin(TWO_PI * f * t + p)
    scale = peak / float(np.max(np.abs(s)))
    return [Tone(float(f), float(scale), float(p)) for f, p in zip(freqs, phases)]


def self_test_stimulus(sample_rate_hz: int = 192000, pilot_hz: float = 2000.0, pilot2_hz: float = 2300.0, cal_hz: float = 1000.0,
                       pilot_amp: float = 0.2, cal_amp: float = 0.25, program_peak: float = 0.5,
                       seed: int = 20261006, n_tones: int = 31, f_lo: float = 50.0, f_hi: float = 18000.0) -> Stimulus:
    """CHAIN-EXP-016 layout, ≤ 2.3 s total (compatible with the SP sound-length limit used for later hardware stimuli).

    Layout: silence | pilot_start | silence | calibration 1 kHz | silence | program multitone | silence | pilot_end | silence.
    The pilot is a two-tone burst (pilot_hz + pilot2_hz, 100 Hz common divisor) so that the pilot
    cross-correlation has one dominant peak (cycle ambiguity margin ~20 % instead of ~0.25 % for a
    single tone); the first tone carries the sub-sample phase estimate.
    """
    segs = [
        Segment("silence_0", 0.000, 0.050, [], role="silence"),
        Segment("pilot_start", 0.050, 0.250, [Tone(pilot_hz, pilot_amp), Tone(pilot2_hz, pilot_amp)], role="pilot_start"),
        Segment("silence_1", 0.300, 0.050, [], role="silence"),
        Segment("calibration", 0.350, 0.500, [Tone(cal_hz, cal_amp)], role="calibration"),
        Segment("silence_2", 0.850, 0.050, [], role="silence"),
        Segment("program", 0.900, 1.100, multitone(n_tones, f_lo, f_hi, seed, program_peak), edge_s=0.010, role="program"),
        Segment("silence_3", 2.000, 0.050, [], role="silence"),
        Segment("pilot_end", 2.050, 0.200, [Tone(pilot_hz, pilot_amp), Tone(pilot2_hz, pilot_amp)], role="pilot_end"),
        Segment("silence_4", 2.250, 0.050, [], role="silence"),
    ]
    return Stimulus(sample_rate_hz, segs, description="CHAIN-EXP-016 synthetic truth; SIMULATION; no hardware meaning")
